export const CompareCardConstant = {
    COMPARE_CARD_CONSTANT_REQUEST: 'COMPARE_CARD_CONSTANT_REQUEST',
    COMPARE_CARD_CONSTANT_SUCCESS: 'COMPARE_CARD_CONSTANT_SUCCESS',
    COMPARE_CARD_CONSTANT_FAILURE: 'COMPARE_CARD_CONSTANT_FAILURE',
};
