export const CustomerUserCardConstant = {
    CUSTOMERUSER_CARD_CONSTANT_REQUEST: 'CUSTOMERUSER_CARD_CONSTANT_REQUEST',
    CUSTOMERUSER_CARD_CONSTANT_SUCCESS: 'CUSTOMERUSER_CARD_CONSTANT_SUCCESS',
    CUSTOMERUSER_CARD_CONSTANT_FAILURE: 'CUSTOMERUSER_CARD_CONSTANT_FAILURE',
};
